"""Traceable offline fixtures for observing rank fusion.

The records keep the IDs and provenance used in lessons 3.3–3.4.  The ranked
lists are deliberately frozen, plausible successes and failures of two
different retrievers.  They are not generated by the exercise and are not a
benchmark for a particular embedding model.  Replace them with real retriever
outputs when transferring the pipeline to your corpus.
"""


IOS_LAUNCH = "sample_report.md#chunk-0000"
SAFETY_GATE = "sample_report.md#chunk-0002"
PILOT_METRICS = "sample_report.md#chunk-0004"
REPORT_OWNER = "sample_report.md#chunk-0005"


SAMPLE_RECORDS = [
    {
        "id": IOS_LAUNCH,
        "source": "sample_report.md",
        "index": 0,
        "word_start": 0,
        "word_end": 70,
        "text": (
            "Ограниченный пилот нового платёжного потока запускается 18 сентября "
            "для 10% пользователей iOS. Android и веб в этот этап не входят."
        ),
    },
    {
        "id": SAFETY_GATE,
        "source": "sample_report.md",
        "index": 2,
        "word_start": 120,
        "word_end": 190,
        "text": (
            "Если согласование службы безопасности не получено к 16 сентября, "
            "запуск переносится. Это обязательный gate запуска."
        ),
    },
    {
        "id": PILOT_METRICS,
        "source": "sample_report.md",
        "index": 4,
        "word_start": 240,
        "word_end": 310,
        "text": (
            "Утверждены две метрики пилота: доля успешных оплат и число обращений "
            "в поддержку. Их смотрят отдельно для пилота и контроля."
        ),
    },
    {
        "id": REPORT_OWNER,
        "source": "sample_report.md",
        "index": 5,
        "word_start": 300,
        "word_end": 370,
        "text": (
            "Команда поддержки сообщает динамику обращений. Ответственный за "
            "итоговый отчёт пока не назначен; его назначает владелец продукта."
        ),
    },
]


EVAL_CASES = [
    {
        "id": "exact-launch",
        "query": "какая доля пользователей iOS участвует и когда старт",
        "expected_ids": [IOS_LAUNCH],
        "rankings": {
            "lexical": [IOS_LAUNCH],
            "dense": [SAFETY_GATE, IOS_LAUNCH],
        },
    },
    {
        "id": "owner-paraphrase",
        "query": "кто автор финального документа",
        "expected_ids": [REPORT_OWNER],
        "rankings": {
            "lexical": [],
            "dense": [REPORT_OWNER],
        },
    },
    {
        "id": "safety-gate",
        "query": "что произойдёт без согласования безопасности",
        "expected_ids": [SAFETY_GATE],
        "rankings": {
            "lexical": [SAFETY_GATE],
            "dense": [SAFETY_GATE, IOS_LAUNCH],
        },
    },
    {
        "id": "pilot-metrics",
        "query": "какие метрики пилота утверждены",
        "expected_ids": [PILOT_METRICS],
        "rankings": {
            "lexical": [PILOT_METRICS],
            "dense": [REPORT_OWNER],
        },
    },
    {
        "id": "outside-corpus",
        "query": "какой рекламный бюджет",
        "expected_ids": [],
        "rankings": {
            "lexical": [],
            "dense": [],
        },
    },
    {
        "id": "support-role",
        "query": "кто сообщает динамику обращений",
        "expected_ids": [REPORT_OWNER],
        "rankings": {
            "lexical": [PILOT_METRICS],
            "dense": [REPORT_OWNER],
        },
    },
]
