"""Traceable offline fixtures for observing rank fusion.

The records are copied verbatim from lesson 3.4: the same stable ID must never
refer to shortened or otherwise changed text.  The ranked lists are deliberately
frozen, plausible successes and failures of two different retrievers.  They are
not generated by the exercise and are not a benchmark for a particular
embedding model.  Replace them with real retriever outputs when transferring
the pipeline to your corpus.
"""


IOS_LAUNCH = "sample_report.md#chunk-0000"
SAFETY_GATE = "sample_report.md#chunk-0002"
PILOT_METRICS = "sample_report.md#chunk-0004"
REPORT_OWNER = "sample_report.md#chunk-0005"


SAMPLE_RECORDS = [
    {
        "id": IOS_LAUNCH,
        "source": "sample_report.md",
        "index": 0,
        "word_start": 0,
        "word_end": 70,
        "text": (
            "# Учебный отчёт о пилоте нового платёжного потока ## 1. Контекст и "
            "границы пилота Команда готовит ограниченный пилот нового платёжного "
            "потока. Принято решение запустить его 18 сентября для 10% "
            "пользователей iOS. Пользователи Android и веб-версии в этот этап не "
            "входят. Цель пилота — проверить техническую стабильность потока и "
            "влияние на обращения в поддержку до решения о дальнейшем расширении. "
            "Объём 10% выбран как контролируемая стартовая группа. В обсуждении "
            "звучали варианты 5%"
        ),
    },
    {
        "id": SAFETY_GATE,
        "source": "sample_report.md",
        "index": 2,
        "word_start": 120,
        "word_end": 190,
        "text": (
            "не принимает решение за службу безопасности. Если согласование не "
            "получено к 16 сентября, запуск переносится. Это условие является "
            "обязательным gate запуска, а не рекомендацией. Новая дата в таком "
            "случае должна быть согласована отдельно; в текущем протоколе она не "
            "определена. ## 3. План запуска В день пилота команда планирует "
            "включать поток постепенно и следить за техническими ошибками. При "
            "критическом росте неуспешных оплат включение останавливается, после "
            "чего трафик возвращается на прежний поток."
        ),
    },
    {
        "id": PILOT_METRICS,
        "source": "sample_report.md",
        "index": 4,
        "word_start": 240,
        "word_end": 310,
        "text": (
            "пилота утверждены две основные метрики: доля успешных оплат и число "
            "обращений в поддержку. Дополнительно команда хочет наблюдать время "
            "ответа платёжного сервиса, но порог для этой метрики ещё не "
            "согласован. Метрики следует смотреть отдельно для пилотной группы и "
            "контрольного потока. Складывать обращения двух групп в одно число "
            "нельзя: это скроет различие, ради которого проводится пилот. ## 5. "
            "Коммуникация и ответственность Статус пилота будет публиковаться во "
            "внутреннем канале проекта. Рита сообщает только"
        ),
    },
    {
        "id": REPORT_OWNER,
        "source": "sample_report.md",
        "index": 5,
        "word_start": 300,
        "word_end": 370,
        "text": (
            "пилота будет публиковаться во внутреннем канале проекта. Рита "
            "сообщает только статус передачи схемы и полученного ответа "
            "безопасности. Команда поддержки сообщает динамику обращений, а "
            "техническая команда — ошибки и время ответа. Ответственный за "
            "итоговый отчёт пока не назначен. Владелец продукта должен назначить "
            "его до запуска. Нельзя автоматически считать Риту владельцем "
            "итогового отчёта только потому, что она указана в разделе о "
            "согласовании. ## 6. Открытые вопросы До запуска остаются три открытых "
            "вопроса:"
        ),
    },
]


EVAL_CASES = [
    {
        "id": "exact-launch",
        "query": "какая доля пользователей iOS участвует и когда старт",
        "expected_ids": [IOS_LAUNCH],
        "rankings": {
            "lexical": [IOS_LAUNCH],
            "dense": [SAFETY_GATE, IOS_LAUNCH],
        },
    },
    {
        "id": "owner-paraphrase",
        "query": "кто автор финального документа",
        "expected_ids": [REPORT_OWNER],
        "rankings": {
            "lexical": [],
            "dense": [REPORT_OWNER],
        },
    },
    {
        "id": "safety-gate",
        "query": "что произойдёт без согласования безопасности",
        "expected_ids": [SAFETY_GATE],
        "rankings": {
            "lexical": [SAFETY_GATE],
            "dense": [SAFETY_GATE, IOS_LAUNCH],
        },
    },
    {
        "id": "pilot-metrics",
        "query": "какие метрики пилота утверждены",
        "expected_ids": [PILOT_METRICS],
        "rankings": {
            "lexical": [PILOT_METRICS],
            "dense": [REPORT_OWNER],
        },
    },
    {
        "id": "outside-corpus",
        "query": "какой рекламный бюджет",
        "expected_ids": [],
        "rankings": {
            "lexical": [],
            "dense": [],
        },
    },
    {
        "id": "support-role",
        "query": "кто сообщает динамику обращений",
        "expected_ids": [REPORT_OWNER],
        "rankings": {
            "lexical": [PILOT_METRICS],
            "dense": [REPORT_OWNER],
        },
    },
]
